### ISSUE TITLE
Lecture Notes

### ISSUE THREAD

**Issue by meliapetersen** [DS4PS/cpp-529-master#7]
I was wondering if there is somewhere we can get the PDFs of the lecture notes. It looked like for week one, one of the sets from the video were posted, but I don't see links on this weeks videos. The videos had resources on census data that I would like to be able to access but I cannot find where to download the notes! 

Thanks :)

**Comment by castower** [comment]
An html and pdf version of the notes are listed under one of the tabs for
week 2. I'm not at my computer right now to figure out which tab, but if
you look you should see them highlighted in blue.

-Courtney

**Comment by meliapetersen** [comment]
So I see that for the video on measurement from last week but they don't seem to be there for the videos this week (maybe I'm just blind and totally missing them haha). Were you able to download them for this week?

**Comment by castower** [comment]
Yes, if you look under the Unit Overview tab, you should see the links in the last paragraph:

> The lecture notes accompanying the videos can be found at the following links: HTML; PDF

**Comment by meliapetersen** [comment]
Ahhhh thank you!!! I just needed to refresh my page, they weren't posted the last time I looked.

**Comment by castower** [comment]
You're welcome!

**Comment by sunaynagoel** [comment]
Thank you i was wondering the same.

**Comment by AntJam-Howell** [comment]
Thanks @castower!
